# Generated by Django 5.0.6 on 2024-05-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driverID', models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=12)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('distance', models.FloatField(default=0)),
                ('vehicle_type', models.CharField(default='', max_length=20)),
                ('rating', models.FloatField(default=5)),
                ('available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('rideID', models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('userID', models.IntegerField(default=1)),
                ('driverID', models.IntegerField(default=1)),
                ('start_lat', models.FloatField(default=0)),
                ('end_lat', models.FloatField(default=0)),
                ('start_long', models.FloatField(default=0)),
                ('end_long', models.FloatField(default=0)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=12)),
                ('password', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
