# Generated by Django 5.0.6 on 2024-05-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assigner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driverID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
