# Generated by Django 5.0.6 on 2024-05-11 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assigner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rides',
        ),
    ]
