# Generated by Django 5.0.6 on 2024-05-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assigner', '0002_delete_rides'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('rideID', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.IntegerField(default=1)),
                ('driverID', models.IntegerField(default=1)),
                ('start_lat', models.FloatField(default=0)),
                ('end_lat', models.FloatField(default=0)),
                ('start_long', models.FloatField(default=0)),
                ('end_long', models.FloatField(default=0)),
                ('time', models.TimeField(auto_now_add=True)),
                ('advanced_booking', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
