# Generated by Django 5.0.6 on 2024-05-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assigner', '0002_alter_driver_driverid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='rideID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
