# Generated by Django 5.0.6 on 2024-05-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assigner', '0004_delete_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driverID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100, unique=True)),
                ('phone', models.CharField(default='', max_length=12, unique=True)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('vehicle_type', models.CharField(default='', max_length=20)),
                ('rating', models.FloatField(default=5)),
                ('available', models.BooleanField(default=False)),
            ],
        ),
    ]
