# Generated by Django 5.0.6 on 2024-05-11 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assigner', '0005_driver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ride',
        ),
    ]
