# Generated by Django 5.0.6 on 2024-05-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assigner', '0007_ride'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
