# Generated by Django 5.0.6 on 2024-05-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='vehicle_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
