# Generated by Django 5.0.6 on 2024-06-09 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0002_driver_vehicle_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Ride',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
